apiVersion: v1
kind: Service
metadata:
  name: registry-svc-write
  labels:
      app: phnmnl-registry-write
spec:
  type: NodePort
  ports:
   - name: http 
     port: 5000
     nodePort: 30750
  selector:
     app: phnmnl-registry-write
