apiVersion: v1
kind: ReplicationController
metadata:
  name: phnmnl-registry-read
spec:
  replicas: 1
  template:
    metadata:
      labels:
         app: phnmnl-registry-read
    spec:
      containers:
      - name: docker-registry
        image: registry:2.5
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: registry-config
            mountPath: /etc/docker/registry
            readOnly: true
      volumes:
        - name: registry-config
          secret: 
             secretName: phenomenal-s3-ebi-registry-access-read
