apiVersion: v1
kind: Service
metadata:
  name: registry-svc-read
  labels:
      app: phnmnl-registry-read
spec:
  type: NodePort
  ports:
   - name: http 
     port: 5000
     nodePort: 30751
  selector:
     app: phnmnl-registry-read
