apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc-web
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
   - name: http 
     port: 8080
     nodePort: 30752
  selector:
    app: jenkins
