apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "cinder-jenkins" 
spec:
  capacity:
    storage: "10Gi" 
  accessModes:
    - "ReadWriteOnce"
  cinder: 
    fsType: "ext4" 
    volumeID: ""
